plugin: aws_ec2 
regions:
 - us-east-1   	 
keyed_groups:
 - key: tags.Name
   prefix: ""
 - key: tags.env
   prefix: ""
filters:
  instance-state-name: running
compose:
  ansible_host: public_ip_address

